use alloc::vec::Vec;
use crate::symbol::SymbolId;

/// Architectural preference types for candidate operator selection.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PreferenceType {
    /// Asserts that an operator is a candidate for selection (`+`).
    Acceptable,
    /// Explicitly prevents an operator from being selected (`-`).
    Reject,
    /// Asserts that an operator must be selected if acceptable (`!`).
    Require,
    /// Prohibits an operator under all circumstances (`~`).
    Prohibit,
    /// Asserts that operator A is strictly preferred over operator B (`>`).
    Better(SymbolId),
    /// Asserts that operator A is less preferred than operator B (`<`).
    Worse(SymbolId),
    /// Declares operator as top tier (`>`).
    Best,
    /// Declares operator as bottom tier (`<`).
    Worst,
    /// Declares that choice among candidates can be arbitrary (`=`).
    Indifferent,
}

/// A preference assertion generated by a production rule during Proposal.
#[derive(Debug, Clone)]
pub struct Preference {
    /// Target state identifier (e.g., `S1`).
    pub state: SymbolId,
    /// Candidate operator identifier (e.g., `O1`).
    pub operator: SymbolId,
    /// Specific preference semantics.
    pub preference_type: PreferenceType,
}

/// Outcome of the Preference Resolution decision phase.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DecisionResult {
    /// Exactly one operator was unambiguously selected.
    Selected(SymbolId),
    /// Multiple acceptable operators exist with no distinguishing preferences.
    TieImpasse(Vec<SymbolId>),
    /// Contradictory preferences prevent selection (e.g., A > B and B > A).
    ConflictImpasse(Vec<SymbolId>),
    /// No acceptable operators were proposed.
    NoChangeImpasse,
}

/// Evaluates active preferences for a given state context and resolves candidate operators.
pub fn resolve_preferences(state: SymbolId, preferences: &[Preference]) -> DecisionResult {
    // 1. Collect all candidates with Acceptable (+) preferences for this state
    let mut candidates: Vec<SymbolId> = preferences
        .iter()
        .filter(|p| p.state == state && p.preference_type == PreferenceType::Acceptable)
        .map(|p| p.operator)
        .collect();

    if candidates.is_empty() {
        return DecisionResult::NoChangeImpasse;
    }

    // Deduplicate candidate list
    candidates.sort();
    candidates.dedup();

    // 2. Filter out candidates with Reject (-) or Prohibit (~) preferences
    candidates.retain(|&cand| {
        !preferences.iter().any(|p| {
            p.state == state
                && p.operator == cand
                && matches!(p.preference_type, PreferenceType::Reject | PreferenceType::Prohibit)
        })
    });

    if candidates.is_empty() {
        return DecisionResult::NoChangeImpasse;
    }

    if candidates.len() == 1 {
        return DecisionResult::Selected(candidates[0]);
    }

    // 3. Evaluate Require (!) preferences
    let required: Vec<SymbolId> = candidates
        .iter()
        .cloned()
        .filter(|&cand| {
            preferences.iter().any(|p| {
                p.state == state
                    && p.operator == cand
                    && p.preference_type == PreferenceType::Require
            })
        })
        .collect();

    if required.len() == 1 {
        return DecisionResult::Selected(required[0]);
    } else if required.len() > 1 {
        return DecisionResult::ConflictImpasse(required);
    }

    // 4. Apply Better (>) / Worse (<) binary ordering filters
    let mut dominates = Vec::new();
    for &a in &candidates {
        let is_dominated = candidates.iter().any(|&b| {
            if a == b {
                return false;
            }
            // b is better than a OR a is worse than b
            preferences.iter().any(|p| {
                (p.state == state && p.operator == b && p.preference_type == PreferenceType::Better(a))
                    || (p.state == state && p.operator == a && p.preference_type == PreferenceType::Worse(b))
            })
        });

        if !is_dominated {
            dominates.push(a);
        }
    }

    if dominates.len() == 1 {
        return DecisionResult::Selected(dominates[0]);
    }

    // Check for binary conflicts (e.g. cycle A > B and B > A resulting in 0 dominant nodes)
    if dominates.is_empty() {
        return DecisionResult::ConflictImpasse(candidates);
    }

    // 5. Check Best / Worst unary preferences
    let best_candidates: Vec<SymbolId> = dominates
        .iter()
        .cloned()
        .filter(|&cand| {
            preferences.iter().any(|p| {
                p.state == state && p.operator == cand && p.preference_type == PreferenceType::Best
            })
        })
        .collect();

    if best_candidates.len() == 1 {
        return DecisionResult::Selected(best_candidates[0]);
    } else if best_candidates.len() > 1 {
        return DecisionResult::TieImpasse(best_candidates);
    }

    // 6. Check if remaining candidates are Indifferent (=)
    let all_indifferent = dominates.iter().all(|&cand| {
        preferences.iter().any(|p| {
            p.state == state
                && p.operator == cand
                && p.preference_type == PreferenceType::Indifferent
        })
    });

    if all_indifferent {
        // Deterministic first choice for no_std flight predictability
        return DecisionResult::Selected(dominates[0]);
    }

    // Default to Tie Impasse when multiple valid candidates remain unresolved
    DecisionResult::TieImpasse(dominates)
}