//! Explanation-Based Learning (Chunking) for automatic rule synthesis.

use alloc::vec::Vec;
use crate::agent::Action;
use crate::rete::{AlphaTest, VariableBinding};

/// A dynamically synthesized production rule (Chunk) compiled from an impasse resolution.
#[derive(Debug, Clone)]
pub struct LearnedChunk {
    /// Generated identifier label for the chunk rule.
    pub name: &'static str,
    /// Conditions grounded in the superstate that led to the substate result.
    pub conditions: Vec<(AlphaTest, Vec<VariableBinding>)>,
    /// Actions targeting the superstate.
    pub actions: Vec<Action>,
}

/// Dynamic chunk builder analyzing substate backtraces to construct learned rules.
#[derive(Debug, Default)]
pub struct ChunkBuilder {
    /// Total count of chunks generated by the agent.
    pub chunk_counter: usize,
}

impl ChunkBuilder {
    /// Creates a new `ChunkBuilder` instance.
    pub fn new() -> Self {
        Self { chunk_counter: 0 }
    }

    /// Synthesizes a chunk from superstate conditions and a resulting superstate action.
    pub fn build_chunk(
        &mut self,
        superstate_conditions: Vec<(AlphaTest, Vec<VariableBinding>)>,
        result_action: Action,
    ) -> LearnedChunk {
        self.chunk_counter += 1;
        LearnedChunk {
            name: "chunk-learned-rule",
            conditions: superstate_conditions,
            actions: alloc::vec![result_action],
        }
    }
}