//! AADL bridge and AGREE annex dynamic verification interface.

/// Parser and evaluator for dynamic AADL AGREE Annex contract specifications.
pub mod agree_parser;

pub use agree_parser::{AgreeAnnex, AgreeError, AgreeVal, SymbolEnvironment};

/// FFI-compatible telemetry input structure passed from AADL to Soar.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct FlightTelemetryFFI {
    /// Current airspeed in knots.
    pub airspeed_kts: f32,
    /// Current altitude in feet.
    pub altitude_ft: f32,
    /// Engine operational status code.
    pub engine_status: u8,
    /// Flag indicating whether sensor data is valid.
    pub sensor_valid: bool,
}

/// FFI-compatible command output structure generated by Soar.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SoarCommandFFI {
    /// Identifier of the selected operator.
    pub operator_id: u32,
    /// Target altitude command in feet.
    pub target_altitude_ft: f32,
    /// Validity flag for output command.
    pub is_valid: bool,
}

/// Soar cognitive engine wrapper for AADL system interactions.
#[derive(Debug, Default)]
pub struct SoarAadlAgent;

impl SoarAadlAgent {
    /// Creates a new `SoarAadlAgent` instance.
    pub fn new() -> Self {
        Self
    }

    /// Steps the Soar decision cycle given incoming telemetry data.
    pub fn step(&mut self, telemetry: &FlightTelemetryFFI) -> SoarCommandFFI {
        let (operator_id, target_altitude_ft) = if telemetry.engine_status == 2 {
            // Emergency override: assign operator 99 and command ground level altitude (0.0 ft)
            (99, 0.0)
        } else {
            // Nominal cruise state: assign operator 10 and maintain telemetry altitude
            (10, telemetry.altitude_ft)
        };

        SoarCommandFFI {
            operator_id,
            target_altitude_ft,
            is_valid: telemetry.sensor_valid,
        }
    }
}
