use alloc::vec::Vec;
use crate::decision::Preference;
use crate::rete::beta::TokenKey;

/// Unique identifier for a registered production rule.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ProductionId(pub u32);

/// Terminal node at the bottom of the Beta network representing a fully satisfied rule condition.
#[derive(Debug, Clone)]
pub struct ProductionNode {
    /// Unique production identifier
    pub id: ProductionId,
    /// Associated parent Beta Memory storing activation tokens
    pub parent_beta_memory: usize,
}

/// Represents a fully matched production instance ready to generate preferences during Elaboration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Instantiation {
    /// Identifier of the production rule that matched
    pub production_id: ProductionId,
    /// The terminal token key satisfying the rule's conditions
    pub token: TokenKey,
    /// Candidate preferences generated by evaluating the RHS of the production
    pub preferences: Vec<Preference>,
}