[package]
name = "rusty-soar-core"
version = "1.0.0"
edition = "2021"
build = "build.rs"
include = ["src/**/*", "rules/**/*", "build.rs", "Cargo.toml"]
description = "Core cognitive kernel for rusty-soar supporting RETE, TMS, EPMEM, SMEM, and RL."

[dependencies]
hashbrown = { workspace = true }
heapless = "0.9.3"
slotmap = { workspace = true }

[dev-dependencies]
